import Link from "next/link";

export const metadata = {
  title: "Disclaimer — Global App & SaaS Revenue Simulator",
  description: "Disclaimer for the Global App & SaaS Revenue Simulator.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col">
      <header className="border-b border-zinc-800 px-4 sm:px-6 py-3 sm:py-4 flex items-center gap-2 sm:gap-3 shrink-0">
        <Link href="/" className="flex items-center gap-2 sm:gap-3 hover:opacity-80 transition-opacity min-w-0">
          <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center font-bold text-xs sm:text-sm text-slate-900 shrink-0">G$</div>
          <h1 className="text-sm sm:text-lg font-semibold tracking-tight truncate">
            <span className="sm:hidden">Revenue Simulator</span>
            <span className="hidden sm:inline">Global App &amp; SaaS Revenue Simulator</span>
          </h1>
        </Link>
      </header>

      <main className="flex-1 max-w-3xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <Link href="/" className="text-sm text-teal-400 hover:text-teal-300 transition-colors">← Back to Simulator</Link>

        <article className="mt-6 space-y-5 sm:space-y-6 text-sm sm:text-base text-zinc-300 leading-relaxed">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-zinc-100">Disclaimer</h1>
            <p className="text-xs sm:text-sm text-zinc-500 mt-2">Last updated: August 8, 2026</p>
          </div>

          <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 text-amber-200">
            <p className="font-semibold">⚠️ Important Notice</p>
            <p className="text-sm mt-1 text-amber-100/90">
              This simulator produces illustrative estimates only. It is not tax advice, legal advice, or financial advice. Always consult a qualified professional before making business decisions.
            </p>
          </div>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">1. Informational Purpose Only</h2>
          <p>
            All calculations, charts, and country-level breakdowns generated by the Global App &amp; SaaS Revenue Simulator (&ldquo;the Service&rdquo;) are provided strictly for educational and planning purposes. The Service is designed to help software developers develop rough intuition about the interaction between platform commissions, consumption taxes, and withholding taxes — not to produce authoritative accounting figures.
          </p>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">2. Not Tax, Legal, or Financial Advice</h2>
          <p>
            The information presented by the Service does not constitute tax advice, legal advice, accounting advice, investment advice, or professional consultation of any kind. No attorney-client, accountant-client, or fiduciary relationship is created by your use of the Service. Before making any decision that has financial, tax, or legal consequences — including pricing strategy, market entry, entity structuring, or Small Business Program enrollment — you should consult a qualified tax advisor, certified public accountant, or attorney licensed in the relevant jurisdiction.
          </p>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">3. Data Accuracy &amp; Freshness</h2>
          <p>
            Tax rates and platform commission schedules are sourced from publicly available documentation as of the &ldquo;Last updated&rdquo; date, but they change frequently and without notice. Apple, Google, Stripe, and PayPal may adjust commission rates, transaction fees, or geographic coverage at any time. National and sub-national tax authorities may enact new VAT/GST rates, digital services taxes, or withholding regimes on short timelines. We make no warranty that the rates embedded in the calculator reflect the current state of any specific jurisdiction on the date of your calculation.
          </p>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">4. Calculation Simplifications</h2>
          <p>
            To keep the model tractable, the Service applies several simplifying assumptions that may not match your real-world situation:
          </p>
          <ul className="list-disc pl-6 space-y-1.5">
            <li>Gross sales are divided evenly across selected target markets, which rarely reflects actual geographic distribution.</li>
            <li>Bilateral tax treaties, foreign tax credits, and permanent establishment considerations are not modeled.</li>
            <li>Currency conversion, foreign exchange fees, and platform-specific rounding rules are ignored.</li>
            <li>Chargebacks, refunds, promotional pricing, and family sharing revenue splits are not considered.</li>
            <li>Corporate income tax, employment taxes, and other post-net-revenue obligations are outside the scope of this tool.</li>
          </ul>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">5. Platform Trademarks</h2>
          <p>
            &ldquo;App Store&rdquo;, &ldquo;iTunes&rdquo;, and &ldquo;Apple&rdquo; are trademarks of Apple Inc. &ldquo;Google Play&rdquo; and &ldquo;Google&rdquo; are trademarks of Google LLC. &ldquo;Stripe&rdquo; is a trademark of Stripe, Inc. &ldquo;PayPal&rdquo; is a trademark of PayPal Holdings, Inc. This Service is not affiliated with, endorsed by, sponsored by, or associated with any of these companies. All trademark references are nominative and used solely to identify the platforms being modeled.
          </p>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">6. No Guarantee of Outcomes</h2>
          <p>
            Any financial projections, margin estimates, or market comparisons produced by the Service are hypothetical. They should not be interpreted as forecasts of actual business performance. Real revenue outcomes depend on numerous factors — including product-market fit, marketing spend, competitive dynamics, refund rates, and regulatory changes — that no calculator can capture.
          </p>

          <h2 className="text-lg sm:text-xl font-semibold text-zinc-100 pt-4">7. Assumption of Risk</h2>
          <p>
            By using the Service, you acknowledge that any decisions you make based on its output are made entirely at your own risk. The site operator shall not be held liable for any tax underpayments, missed filing obligations, business losses, or other consequences arising from reliance on the calculator&apos;s figures. When in doubt, verify directly with the platform&apos;s current developer documentation and the tax authority of the relevant jurisdiction.
          </p>
        </article>
      </main>

      <footer className="border-t border-zinc-800 px-4 sm:px-6 py-6 text-center text-sm text-zinc-500">
        <p className="text-xs sm:text-sm">&copy; 2026 Global App &amp; SaaS Revenue Simulator. All rights reserved.</p>
        <div className="mt-3 flex justify-center gap-3 sm:gap-4 flex-wrap text-xs sm:text-sm">
          <Link href="/privacy" className="hover:text-zinc-300 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-zinc-300 transition-colors">Terms of Service</Link>
          <Link href="/disclaimer" className="hover:text-zinc-300 transition-colors">Disclaimer</Link>
        </div>
      </footer>
    </div>
  );
}
